### ISSUE TITLE
REGHDFE - installation problems

### ISSUE THREAD

**Issue by andresbarriosf** [sergiocorreia/reghdfe#149]
Hi, 

I've been using reghdfe for a while; I was having some issues with it and I decided to reinstall it and now it is not working:

`ssc install reghdfe
ssc install ftools

ftools, compile
reghdfe, compile`

`reghdfe, version`
 version 5.2.9 06aug2018
Required packages installed?
- ftools            yes

It does not work even with simple regressions:

`. reghdfe price mpg, a(foreign)`
(MWFE estimator converged in 1 iterations)
command reghdfe_store_alphas is unrecognized

` reghdfe price (mpg = weight), a(foreign) 
`
parentheses unbalanced

Any suggestions?

Thanks!!!

**Comment by truan** [comment]
I had the same error message "command reghdfe_store_alphas is unrecognized" after I tried the following commands:

`cap ado uninstall ftools`
`cap ado uninstall reghdfe`
`ssc install ftools`
`ssc install reghdfe`
`reghdfe, version`
c:\ado\plus\r\reghdfe.ado
*! version 5.2.9 06aug2018
`reghdfe...`
(existing lftools.mlib is version "2.14.1 12jul2017"; need to recompile for "2.30.3 02aug2018")
(compiling lftools.mlib for Stata 15.1)
(library saved in c:\ado\plus/l/lftools.mlib)
(existing lreghdfe.mlib compiled with Stata ???; need to recompile for Stata 15.1)
(compiling lreghdfe.mlib for Stata 15.1)
(library saved in c:\ado\plus/l/lreghdfe.mlib)
(MWFE estimator converged in 5 iterations)
command reghdfe_store_alphas is unrecognized

The README file has not updated for version 5.2.9.

**Comment by sergiocorreia** [comment]
Hi Andres, Truan,

There are two do-files currently missing in the SSC version; so for now treat that version as broken and use the Github one.

About the IV example, IV/2SLS regressions should now be done through ivreghdfe: https://github.com/sergiocorreia/ivreghdfe

Best,
Sergio

**Comment by andresbarriosf** [comment]
Thank you, Sergio!

I installed the Github version and it is working perfectly! 

Best, 
AB

**Comment by sergiocorreia** [comment]
By the way, the SSC version should be working now!

**Comment by truan** [comment]
I installed the SSC version. It worked well this time! Thanks!

**Comment by iva-trako** [comment]
Still not working properly:

. reghdfe hv_121 hv104, absorb(i.shdist i.year) cluster (shdist)
(MWFE estimator converged in 3 iterations)
class FixedEffects undefined
r(3000);

**Comment by iva-trako** [comment]
> By the way, the SSC version should be working now!

It still does not work. Could you please check why I get this?

. reghdfe hv_121 hv104, absorb(i.shdist i.year) cluster (shdist)
(MWFE estimator converged in 3 iterations)
class FixedEffects undefined
r(3000);

**Comment by sergiocorreia** [comment]
> > By the way, the SSC version should be working now!
> 
> It still does not work. Could you please check why I get this?
> 
> . reghdfe hv_121 hv104, absorb(i.shdist i.year) cluster (shdist)
> (MWFE estimator converged in 3 iterations)
> class FixedEffects undefined
> r(3000);

That is an unrelated issue, mentioned in the readme, that can be fixed by "reghdfe, compile"

**Comment by iva-trako** [comment]
Yes, it worked! thanks a lot!
